//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS.Bot.WebApi.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HIS.Bot.WebApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jetzt Kochen ähnelt.
        /// </summary>
        public static string ButtonLabel_StartCooking {
            get {
                return ResourceManager.GetString("ButtonLabel_StartCooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bunch(es) ähnelt.
        /// </summary>
        public static string EnumValue_CookingUnit_Bunch {
            get {
                return ResourceManager.GetString("EnumValue_CookingUnit_Bunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die g ähnelt.
        /// </summary>
        public static string EnumValue_CookingUnit_Gramm {
            get {
                return ResourceManager.GetString("EnumValue_CookingUnit_Gramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die kg ähnelt.
        /// </summary>
        public static string EnumValue_CookingUnit_Kilogramm {
            get {
                return ResourceManager.GetString("EnumValue_CookingUnit_Kilogramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die l ähnelt.
        /// </summary>
        public static string EnumValue_CookingUnit_Liter {
            get {
                return ResourceManager.GetString("EnumValue_CookingUnit_Liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mg ähnelt.
        /// </summary>
        public static string EnumValue_CookingUnit_Milligramm {
            get {
                return ResourceManager.GetString("EnumValue_CookingUnit_Milligramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ml ähnelt.
        /// </summary>
        public static string EnumValue_CookingUnit_Milliliter {
            get {
                return ResourceManager.GetString("EnumValue_CookingUnit_Milliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die msp ähnelt.
        /// </summary>
        public static string EnumValue_CookingUnit_Msp {
            get {
                return ResourceManager.GetString("EnumValue_CookingUnit_Msp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string EnumValue_CookingUnit_None {
            get {
                return ResourceManager.GetString("EnumValue_CookingUnit_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Package(s) ähnelt.
        /// </summary>
        public static string EnumValue_CookingUnit_Package {
            get {
                return ResourceManager.GetString("EnumValue_CookingUnit_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tbl ähnelt.
        /// </summary>
        public static string EnumValue_CookingUnit_Tablespoon {
            get {
                return ResourceManager.GetString("EnumValue_CookingUnit_Tablespoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tsp ähnelt.
        /// </summary>
        public static string EnumValue_CookingUnit_Teaspoon {
            get {
                return ResourceManager.GetString("EnumValue_CookingUnit_Teaspoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Gericht ist fertig. Guten Appetit. ähnelt.
        /// </summary>
        public static string Message_CookingCompleted {
            get {
                return ResourceManager.GetString("Message_CookingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tut mir leid. Ich verstehe dich nicht ähnelt.
        /// </summary>
        public static string Message_DontUnderstand {
            get {
                return ResourceManager.GetString("Message_DontUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das habe ich leider nicht verstanden ähnelt.
        /// </summary>
        public static string Message_Error_DontUnderstand {
            get {
                return ResourceManager.GetString("Message_Error_DontUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du musst zuerst ein Rezept auswählen, bevor du dir die Zutatenliste angucken kannst ähnelt.
        /// </summary>
        public static string Message_Error_NoRecipeIdFoundForIngrediantslist {
            get {
                return ResourceManager.GetString("Message_Error_NoRecipeIdFoundForIngrediantslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du musst zuerst ein Rezept auswählen ähnelt.
        /// </summary>
        public static string Message_Error_NoRecipePicked {
            get {
                return ResourceManager.GetString("Message_Error_NoRecipePicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für deine Anfrage habe ich keine Rezepte gefunden ähnelt.
        /// </summary>
        public static string Message_Error_NoRecipesFound {
            get {
                return ResourceManager.GetString("Message_Error_NoRecipesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es muss zuerst ein Rezept gewählt werden, das Kochen gestartet werden kann ähnelt.
        /// </summary>
        public static string Message_Error_RecipeMustBeSelectedFirst {
            get {
                return ResourceManager.GetString("Message_Error_RecipeMustBeSelectedFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rezept wurde nicht gefunden ähnelt.
        /// </summary>
        public static string Message_Error_RecipeNotFound {
            get {
                return ResourceManager.GetString("Message_Error_RecipeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Laden des Rezepteschritts. Falls dieser Fehler häufiger auftauche, wende dich bitte an deinen Admin ähnelt.
        /// </summary>
        public static string Message_Error_UnableToReceiveStep {
            get {
                return ResourceManager.GetString("Message_Error_UnableToReceiveStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die von ähnelt.
        /// </summary>
        public static string Message_of {
            get {
                return ResourceManager.GetString("Message_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich habe folgende Rezepte gefunden ähnelt.
        /// </summary>
        public static string Message_RecipesFound {
            get {
                return ResourceManager.GetString("Message_RecipesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du kannst während des Kochens zwischen den einzelnen Schritten vor und zurücknavigieren oder dir die Zutatenliste anzeigen lassen. ähnelt.
        /// </summary>
        public static string Message_StartCooking_Desc {
            get {
                return ResourceManager.GetString("Message_StartCooking_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Los gehts ähnelt.
        /// </summary>
        public static string Message_StartCooking_HereWeGo {
            get {
                return ResourceManager.GetString("Message_StartCooking_HereWeGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schritt ähnelt.
        /// </summary>
        public static string Message_Step {
            get {
                return ResourceManager.GetString("Message_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schritten ähnelt.
        /// </summary>
        public static string Message_Steps {
            get {
                return ResourceManager.GetString("Message_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo. Ich bin ein Rezepte-Bot. Du kannst mich nach tollen Rezepten fragen. Nachdem du ein Rezept ausgewählt hast, werde ich dich beim Kochen begleiten. ähnelt.
        /// </summary>
        public static string Message_Welcome {
            get {
                return ResourceManager.GetString("Message_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für dein Rezept werden folgende Zutaten benötigt: ähnelt.
        /// </summary>
        public static string Message_YouNeedFollingIngrediants {
            get {
                return ResourceManager.GetString("Message_YouNeedFollingIngrediants", resourceCulture);
            }
        }
    }
}
